export type Professional={id:string;slug:string;name:string;trade:string;category:string;zone:string;description:string;years:number;home:boolean;quotes:boolean;rating:number;reviews:number;jobs:number;available:boolean;services:string[];hours:string;whatsapp:string;badges:string[];photos:string[]};
export const categories=[['🏠','Construcción y reparaciones'],['⚡','Electricidad'],['🔥','Gas'],['🚰','Plomería'],['🎨','Pintura'],['🪚','Carpintería'],['🔩','Herrería'],['🧵','Costura y confección'],['🌱','Jardinería'],['🧹','Limpieza'],['💇','Belleza'],['🚗','Automotor'],['📱','Tecnología'],['🐶','Mascotas'],['👶','Cuidado'],['🚚','Fletes y mudanzas'],['🍰','Cocina y repostería'],['🛠️','Otros servicios']].map(([icon,name])=>({icon,name,slug:name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replaceAll(' ','-').replaceAll('y-','')}));
export const professionals:Professional[]=[
{id:'1',slug:'carlos-albanileria',name:'Carlos',trade:'Albañilería',category:'Construcción y reparaciones',zone:'Centro y barrios cercanos',description:'Trabajos de albañilería, reparaciones y mantenimiento general. Atención a domicilio.',years:12,home:true,quotes:true,rating:4.9,reviews:18,jobs:73,available:true,services:['Reparación de paredes','Revoques','Pisos','Mantenimiento'],hours:'Lun a sáb · 8:00 a 18:00',whatsapp:'5490000000001',badges:['Perfil completo','Recomendado por usuarios'],photos:['/placeholder-work.svg','/placeholder-work.svg']},
{id:'2',slug:'maria-costura',name:'María',trade:'Costura y arreglos',category:'Costura y confección',zone:'Pergamino',description:'Arreglos de ropa, costura y confección. Consultá por prendas a medida.',years:9,home:false,quotes:true,rating:5,reviews:11,jobs:42,available:true,services:['Arreglos de ropa','Dobladillos','Cierres','Prendas a medida'],hours:'Lun a vie · 9:00 a 17:00',whatsapp:'5490000000002',badges:['Perfil completo','WhatsApp verificado'],photos:['/placeholder-work.svg','/placeholder-work.svg']},
{id:'3',slug:'juan-electricidad',name:'Juan',trade:'Electricista',category:'Electricidad',zone:'Barrio Acevedo y Centro',description:'Instalaciones, reparaciones eléctricas y mantenimiento domiciliario.',years:7,home:true,quotes:true,rating:4.7,reviews:9,jobs:31,available:true,services:['Instalaciones','Reparaciones','Tableros','Iluminación'],hours:'Lun a sáb · 8:00 a 19:00',whatsapp:'5490000000003',badges:['Perfil completo'],photos:['/placeholder-work.svg']},
{id:'4',slug:'laura-limpieza',name:'Laura',trade:'Limpieza',category:'Limpieza',zone:'Toda la ciudad',description:'Limpieza de casas, oficinas y alquileres temporarios. Turnos coordinados.',years:5,home:true,quotes:true,rating:4.8,reviews:14,jobs:58,available:true,services:['Limpieza general','Limpieza profunda','Oficinas'],hours:'Lun a sáb · 8:00 a 16:00',whatsapp:'5490000000004',badges:['Perfil completo','Recomendado por usuarios'],photos:['/placeholder-work.svg']}
];
export const requests=[{id:'r1',title:'Necesito arreglar una campera',category:'Costura y confección',service:'Arreglos de ropa',zone:'Pergamino',description:'Se rompió el cierre de una campera y necesito repararlo.',date:'Esta semana'},{id:'r2',title:'Pintar una habitación',category:'Pintura',service:'Pintura interior',zone:'Centro',description:'Busco presupuesto para pintar una habitación.',date:'Próxima semana'},{id:'r3',title:'Reparar una pérdida de agua',category:'Plomería',service:'Pérdidas y canillas',zone:'Barrio Acevedo',description:'Tengo una pérdida debajo de la pileta.',date:'Lo antes posible'}];
export const synonyms:Record<string,string[]>={costurera:['costura','modista','arreglo ropa','arreglos de ropa','campera','cierre','ropa'],plomero:['plomería','canilla','pérdida','agua','pileta'],albañil:['albañilería','pared','revoque','piso','construcción'],electricista:['electricidad','eléctrico','enchufe','luz','instalación'],pintor:['pintura','pintar','pared','casa']};
